name: Scrape and Store Data

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-cloud-bigquery pandas pandas-gbq playwright
        playwright install

    - name: Set up BigQuery Authentication
      env:
        BIGQUERY_CREDENTIALS_JSON: ${{ secrets.BIGQUERY_CREDENTIALS_JSON }}
      run: |
        echo "$BIGQUERY_CREDENTIALS_JSON" > bigquery-key.json
        export GOOGLE_APPLICATION_CREDENTIALS=bigquery-key.json

    - name: Run Scraping Script
      run: |
        python tcg_scraping_script.py
      env:
        BIGQUERY_PROJECT_ID: ${{ secrets.BIGQUERY_PROJECT_ID }}
