name: Scrape Images

on:
  workflow_dispatch:  # Allows for manual triggering only

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install  # This installs required browsers

    - name: Configure BigQuery credentials
      env:
        BIGQUERY_CREDENTIALS_JSON: ${{ secrets.BIGQUERY_CREDENTIALS_JSON }}
      run: echo "$BIGQUERY_CREDENTIALS_JSON" > bigquery-key.json

    - name: Run scraping script
      env:
        BIGQUERY_PROJECT_ID: ${{ secrets.BIGQUERY_PROJECT_ID }}
        GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/bigquery-key.json
      run: python code/scraping/tcg_card_image_scraping.py
