name: Scrape Batch 2

on:
  workflow_run:
    workflows: ["Scrape Batch 1"]
    types:
      - completed

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas google-cloud-bigquery playwright
        python -m playwright install

    - name: Install Playwright Browsers
      run: |
        python -m playwright install

    - name: Run scraping script for Batch 2
      env:
        BIGQUERY_PROJECT_ID: ${{ secrets.BIGQUERY_PROJECT_ID }}
        GOOGLE_APPLICATION_CREDENTIALS: bigquery-key.json
      run: |
        echo "$BIGQUERY_CREDENTIALS_JSON" > bigquery-key.json
        python tcg_scraping_script.py --urls-file "sets_2.txt"
