name: Scrape Data

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight; adjust as needed
  workflow_dispatch:  # Allows manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas playwright
        playwright install  # Installs required browser binaries

    - name: Run Scraping Script
      run: |
        python tcg_scraping_script.py

    - name: Commit and Push Results
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        
        git add combined_pokemon_prices.csv
        git commit -m "Update combined CSV with new scraped data" || echo "No changes to commit"
        
        # Pull latest changes from main, rebase, and push
        git pull --rebase origin main
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
