name: Run Set Pull Values Calculation

on:
  workflow_dispatch:

jobs:
  calculate_set_pull_values:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure BigQuery credentials
        env:
          BIGQUERY_CREDENTIALS_JSON: ${{ secrets.BIGQUERY_CREDENTIALS_JSON }}
        run: echo "$BIGQUERY_CREDENTIALS_JSON" > bigquery-key.json

      - name: Run the Set Pull Values Calculation Script
        env:
          BIGQUERY_PROJECT_ID: ${{ secrets.BIGQUERY_PROJECT_ID }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/bigquery-key.json
        run: python code/analytics/best_value_set.py
          
      - name: Upload result CSV to GitHub artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: set_pull_values
          path: data/set_pull_values.csv
