name: Run Scraper Test Cards

on:
  workflow_dispatch:  # Allows for manual triggering only

jobs:
  test_scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install  # This installs required browsers

      - name: Run Scraping Test
        run: |
          python test/test_tcg_card_scraping.py
          
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: scraped_data_test
          path: test/test_card_prices.csv
