name: Upload Images to GCS

on:
  workflow_dispatch:  # Manually triggered from GitHub Actions

jobs:
  upload_images:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install google-cloud-storage google-cloud-bigquery requests


    - name: Configure Google Cloud credentials
      env:
        BIGQUERY_CREDENTIALS_JSON: ${{ secrets.BIGQUERY_CREDENTIALS_JSON }}
      run: |
        echo "$BIGQUERY_CREDENTIALS_JSON" > ${{ runner.temp }}/gcloud-key.json

    - name: Run upload script
      env:
        BIGQUERY_PROJECT_ID: ${{ secrets.BIGQUERY_PROJECT_ID }}
        GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/gcloud-key.json
        GCS_BUCKET_NAME: ${{ secrets.GCS_BUCKET_NAME }}  # Ensure this secret is set for the GCS bucket
      run: python code/scraping/tcg_card_image_upload.py
